#
# 用于 "TestEm6.cc" 初始化阶段的宏文件
#
# 设置默认详细输出级别
# 并初始化图形显示。
#
/control/verbose 2
/run/verbose 2
#

# 注意：想看见移动，可以修改这里
/run/initialize
#/Xray/det/loadGDML /home/yyb/workspace/XRay-all/XRay-detectionCode/build/ore.gdml
#/Xray/det/SetObjShift 0 mm
#/run/reinitializeGeometry


#
# 使用以下打开语句创建 OpenGL 视图：
#/vis/open OGLIX 600x600-0+0
/vis/open OGL 600x600-0+0
#
# 使用以下打开语句创建适用于
# 在 DAWN 中查看的 .prim 文件：
#/vis/open DAWNFILE
#
# 使用以下打开语句创建适用于
# 在 HepRApp 中查看的 .heprep 文件：
#/vis/open HepRepFile
#
# 使用以下打开语句创建适用于
# 在 VRML 查看器中查看的 .wrl 文件：
#/vis/open VRML2FILE
#
# 在建立场景和轨迹期间关闭自动刷新并减少可视化消息输出：
# 轨迹建立时：
/vis/viewer/set/autoRefresh false
/vis/verbose errors
#
# 绘制几何体：
/vis/drawVolume
#
# 指定视角：
/vis/viewer/set/viewpointThetaPhi 135. 15.
#
# 指定缩放值：
/vis/viewer/zoom 1.4
#
# 指定样式（表面或线框）：
/vis/viewer/set/style surface
# 获得更好的视图效果
/vis/geometry/set/visibility World 0 false
#
# 绘制坐标轴：
  /vis/scene/add/axes 0 0 0 10 cm
#
# 在事件结束时绘制平滑轨迹，并显示轨迹点
# 为 2 像素宽的标记：
/vis/scene/add/trajectories smooth
/vis/modeling/trajectories/create/drawByCharge
/vis/modeling/trajectories/drawByCharge-0/default/setDrawStepPts false
/vis/modeling/trajectories/drawByCharge-0/default/setStepPtsSize 1
# (若轨迹过多导致崩溃 => /tracking/storeTrajectory 0)
#
# 在事件结束时绘制击中点：
#/vis/scene/add/hits
#
# 若只绘制 gamma：
#/vis/filtering/trajectories/create/particleFilter
#/vis/filtering/trajectories/particleFilter-0/add gamma
#
# 若反转上述过滤（绘制除 gamma 外所有粒子），
# 保留上面两行并额外添加：
#/vis/filtering/trajectories/particleFilter-0/invert true
#
# /vis/modeling 和 /vis/filtering 提供更多选项。
# 例如，可按粒子 ID 选择颜色：
/vis/modeling/trajectories/create/drawByParticleID
/vis/modeling/trajectories/drawByParticleID-0/set e- red
/vis/modeling/trajectories/drawByParticleID-0/set e+ red
/vis/modeling/trajectories/drawByParticleID-0/set gamma green
/vis/modeling/trajectories/drawByParticleID-0/set neutron yellow
/vis/modeling/trajectories/drawByParticleID-0/set alpha red
/vis/modeling/trajectories/drawByParticleID-0/set GenericIon red
/vis/modeling/trajectories/drawByParticleID-0/set nu_e yellow
/vis/modeling/trajectories/drawByParticleID-0/set anti_nu_e yellow
#
# 叠加某次运行中的所有事件：

/vis/scene/endOfEventAction accumulate

#
# 恢复自动刷新与详细输出：
/vis/viewer/set/autoRefresh true
/vis/verbose warnings
#
# 对于基于文件的驱动，使用此命令创建空探测器视图：
#/vis/viewer/flush
#/control/execute Co60.mac
